apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nextjs-sqlite.fullname" . }}-migrations-{{ .Values.image.tag }}
  labels:
    {{- include "nextjs-sqlite.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['node']
          args: ["/app/dist/migrations"]
          env:
            - name: DATABASE_PATH
              value: /database
          volumeMounts:
          - mountPath: /database
            name: sqlite-database
      volumes:
      - name: sqlite-database
        persistentVolumeClaim:
          claimName: sqlite-database