apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-database
spec:
  accessModes:
  # volume can be mounted as read-write by a single node
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
