import { ColumnType, Generated } from "kysely";

export namespace Tables {
  export interface Migration {
    id: Generated<number>;
    filename: string;
    sha: string;
    created_at: ColumnType<Date, string | undefined, never>;
    updated_at: ColumnType<Date, string | undefined, never>;
  }

  export interface User {
    // Columns that are generated by the database should be marked
    // using the `Generated` type. This way they are automatically
    // made optional in inserts and updates.
    id: Generated<number>;
    first_name: string;
    last_name: string;
    email: string;
    image: string;

    // You can specify a different type for each operation (select, insert and
    // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
    // wrapper. Here we define a column `createdAt` that is selected as
    // a `Date`, can optionally be provided as a `string` in inserts and
    // can never be updated:
    createdAt: ColumnType<Date, string | undefined, never>;
  }
}
